version: '2'
services:
    php:
        build: ./docker/php/
        volumes:
            - ./:/dockerApp
        working_dir: /dockerApp
    web:
        build: ./docker/nginx/
        volumes:
            - ./:/dockerApp
        working_dir: /dockerApp
        depends_on:
          - php
        ports:
          - 80:80
    mysql:
        build: ./docker/mysql/
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        volumes:
            - ./:/dockerApp
            - /opt/mysql_data:/var/lib/mysql
        ports:
            - 6666:3306

